<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>PdfPotpis</AssemblyName>
    <RootNamespace>PdfPotpis</RootNamespace>
    <Product>PDFPotpis</Product>
    <Company>PDFPotpis</Company>
    <ApplicationIcon>..\..\assets\PdfPotpis.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\PdfPotpis.ico" Link="Assets\PdfPotpis.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
  </ItemGroup>

</Project>
